Search for a Ps5 test
Dmaza86/check24-test pull request #1
Opened 2022-01-27 20:31 UTC by Dmaza86

2022-01-27 20:50 UTC, Jose-Luis-Nunez requested changes

2022-01-27 20:50 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/SearchProductTest.kt
> +            offer {
the offer page object is inside the searchResult page object

2022-01-27 20:50 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/SearchProductTest.kt
> +            assertThat(offer.getPs5Description()).isDisplayed
assert is inside the searchResult page object

2022-01-27 20:50 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/SearchResult.kt
> +    fun selectSonyPlaystation() {
this function could be more abstract, imagine we would search for a bike, then this function name would be wrong you can combine something related to the page object name

2022-01-27 20:50 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/Offer.kt
> +    fun getPs5Description(): FluentWebElement {
here also be more abstract because every offer could have a title not only a ps5, you can use something related to the page object

2022-01-27 20:50 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/Offer.kt
> +    fun selectPs5Console() {
here also be more abstract because every offer must not be a ps5, you can use something related to the page object

2022-01-27 20:50 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/Offer.kt
> +    private lateinit var ps5Description: FluentWebElement
here also be more abstract live below

2022-01-27 20:50 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/SearchResult.kt
> +    private lateinit var sonyPlaystationOption: FluentWebElement
here you could also be more abstract

2022-01-27 20:51 UTC, Jose-Luis-Nunez commented
also please add a CI integration with github actions like in the other selenium project

2022-01-28 15:55 UTC, Jose-Luis-Nunez requested changes

2022-01-28 15:55 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/Offer.kt
> +    private lateinit var productSelected: FluentWebElement
why do you need this selector?

2022-01-28 15:55 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/Offer.kt
> +    @FindBy(css = "[data-product-id='26410067']")
dont use in the selector a specific product id, if the product is not available and you see a different product it will fail

2022-01-28 15:55 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/Offer.kt
> +    private lateinit var productDescription: FluentWebElement
it is not a product Description if is an offer title

2022-01-28 15:55 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/Offer.kt
> +    fun selectProduct() {
why do you select a product on the offer page?

2022-01-31 09:03 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/Offer.kt
> +    private lateinit var productSelected: FluentWebElement
this selector allows you to select the product when the user clicks on the area of it

2022-01-31 09:58 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/Offer.kt
> +    fun selectProduct() {
At first, I thought it belongs to the offer object, but it makes sense that it belongs to the search result object

2022-01-31 09:58 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/Offer.kt
> +    private lateinit var productDescription: FluentWebElement
done

2022-01-31 09:58 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/Offer.kt
> +    @FindBy(css = "[data-product-id='26410067']")
done

2022-01-31 15:34 UTC, Jose-Luis-Nunez approved these changes

2022-01-31 15:54 UTC, merged