Half registration
Dmaza86/check24-test pull request #2
Opened 2022-02-11 17:35 UTC by Dmaza86

2022-02-15 23:40 UTC, Jose-Luis-Nunez requested changes

2022-02-15 23:40 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/SearchResultPage.kt
> +    private var firstElement = 0
because this is a constant in kotlin you can write it above the class like

```
...
import org.openqa.selenium.support.FindBy

private const val FIRST_ELEMENT = 0

class SearchResultPage : AbstractScreen() {
...
...
}
```

2022-02-15 23:40 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/SearchResultPage.kt
> +        waitUntilElementNotDisplayed(spinner)
do you really need to wait until the element is not displayed? have you tried without?

2022-02-15 23:40 UTC, Jose-Luis-Nunez commented on src/test/kotlin/tests/RegistrationTest.kt
> +            focusOnLoginModal()
maybe better name for this function?

2022-02-15 23:40 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/RegistrationPage.kt
> +    fun focusOnLoginModal() {
is there no possible way to hide this in other function?  the test would better better readable afterwards

2022-02-16 12:16 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/RegistrationPage.kt
> +    fun focusOnLoginModal() {
I added it to the` fun submitEmail()`

2022-02-16 12:16 UTC, Dmaza86 commented on src/test/kotlin/tests/RegistrationTest.kt
> +            focusOnLoginModal()
I replace it for `getIframe()`

2022-02-16 12:18 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/SearchResultPage.kt
> +    private var firstElement = 0
done

2022-02-16 12:18 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/SearchResultPage.kt
> +        waitUntilElementNotDisplayed(spinner)
without it, the test crashes

2022-02-16 14:47 UTC, Jose-Luis-Nunez requested changes

2022-02-16 14:47 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/SearchResultPage.kt
> +        waitUntilElementNotDisplayed(spinner)
ok

2022-02-16 14:47 UTC, Jose-Luis-Nunez commented on src/test/kotlin/pageobjects/RegistrationPage.kt
> +        return backButton
you return just the element and assert that it is displayed, what if it is not displayed? in all you other tests you handle it differently

2022-02-16 15:49 UTC, Dmaza86 commented on src/test/kotlin/pageobjects/RegistrationPage.kt
> +        return backButton
done

2022-02-16 16:18 UTC, Jose-Luis-Nunez approved these changes

2022-02-16 16:22 UTC, merged